# Generated by Django 4.2.9 on 2024-01-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('S_NO', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=40)),
                ('AGE', models.IntegerField()),
            ],
        ),
    ]
